parameters:


services:
    redis_orm.model_manager:
        class: Goksagun\RedisOrmBundle\ORM\ModelManager

    Goksagun\RedisOrmBundle\ORM\ModelManagerInterface: '@redis_orm.model_manager'

    redis_orm.shard_manager:
        class: Goksagun\RedisOrmBundle\ORM\ShardManager

    Goksagun\RedisOrmBundle\ORM\ShardManagerInterface: '@redis_orm.shard_manager'